//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations;

namespace ChokinCF.Models
{
	public partial class Currency : IId, IAuditable
	{
        #region ' IAuditable '
        [ScaffoldColumn(false)]
        public virtual DateTime CreatedOn { get; set; }
        [ScaffoldColumn(false)]
        public virtual string CreatedUserId { get; set; }
        [ScaffoldColumn(false)]
        public virtual ApplicationUser CreatedUser { get; set; }
        [ScaffoldColumn(false)]
        public virtual DateTime LastModifiedOn { get; set; }
        [ScaffoldColumn(false)]
        public virtual string LastModifiedUserId { get; set; }
        [ScaffoldColumn(false)]
        public virtual ApplicationUser LastModifiedUser { get; set; }
        #endregion
	}
}