//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chokin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalEntry
    {
        public int Id { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime Date { get; set; }
        public string Concept { get; set; }
        public int DebitAccountId { get; set; }
        public int CreditAccountId { get; set; }
        public int CurrencyId { get; set; }
        public int UserId { get; set; }
        public bool IsRecurring { get; set; }
        public bool IsCancelling { get; set; }
    
        public virtual Account CreditAccount { get; set; }
        public virtual Account DebitAccount { get; set; }
        public virtual Currency Currency { get; set; }
    }
}
