//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using ChokinCF.Models;

namespace ChokinCF.Repository
{
    public static class RepositoryFactory
    {
        public static IRepository<Currency> GetCurrencyRepository()
        {
            var context = new ApplicationDbContext();
            return null;
        }
        public static IRepository<Account> GetAccountRepository()
        {
            var context = new ApplicationDbContext();
            return null;
        }
        public static IRepository<AccountType> GetAccountTypeRepository()
        {
            var context = new ApplicationDbContext();
            return null;
        }
    }
}