//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using ChokinCF.Models;

namespace ChokinCF.Repository
{
	public sealed class UnitOfWork : IDisposable
	{
		private RepositoryFactory _factory;
		private ApplicationDbContext _context;
		private bool _disposed;

		public UnitOfWork() 
		{
			_context = new ApplicationDbContext();
			_factory = new RepositoryFactory(_context);
		}

		public void Commit() 
		{
			_context.SaveChanges();
		}

		public void Dispose() 
		{
			Dispose(true);
			GC.SuppressFinalize(this);  
		}

		private void Dispose(bool disposing) 
		{
			if (!_disposed)	 
			{
				_disposed = true;
				_context.Dispose();
			}
		}

		#region ' Repositories '

		public IRepository<Currency> CurrencyRepository { get { return _factory.CurrencyRepository; } }
		public IRepository<Account> AccountRepository { get { return _factory.AccountRepository; } }
		public IRepository<AccountType> AccountTypeRepository { get { return _factory.AccountTypeRepository; } }

		#endregion
	}
}